/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ReNostrPopoverNote {
        "includeQuote": boolean;
        "quotedContent"?: string;
    }
    interface ReNostrPopoverRoot {
    }
}
declare global {
    interface HTMLReNostrPopoverNoteElement extends Components.ReNostrPopoverNote, HTMLStencilElement {
    }
    var HTMLReNostrPopoverNoteElement: {
        prototype: HTMLReNostrPopoverNoteElement;
        new (): HTMLReNostrPopoverNoteElement;
    };
    interface HTMLReNostrPopoverRootElement extends Components.ReNostrPopoverRoot, HTMLStencilElement {
    }
    var HTMLReNostrPopoverRootElement: {
        prototype: HTMLReNostrPopoverRootElement;
        new (): HTMLReNostrPopoverRootElement;
    };
    interface HTMLElementTagNameMap {
        "re-nostr-popover-note": HTMLReNostrPopoverNoteElement;
        "re-nostr-popover-root": HTMLReNostrPopoverRootElement;
    }
}
declare namespace LocalJSX {
    interface ReNostrPopoverNote {
        "includeQuote"?: boolean;
        "quotedContent"?: string;
    }
    interface ReNostrPopoverRoot {
    }
    interface IntrinsicElements {
        "re-nostr-popover-note": ReNostrPopoverNote;
        "re-nostr-popover-root": ReNostrPopoverRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "re-nostr-popover-note": LocalJSX.ReNostrPopoverNote & JSXBase.HTMLAttributes<HTMLReNostrPopoverNoteElement>;
            "re-nostr-popover-root": LocalJSX.ReNostrPopoverRoot & JSXBase.HTMLAttributes<HTMLReNostrPopoverRootElement>;
        }
    }
}
